info:
  description: xxxxxxxxxxxxxxxxxxxxxxXXX
  url: https://github.com/spring-cloud-samples/day

bar: bar
foo: foo

#interval in seconds
spring:
    cloud:
        config:
            refreshInterval: 60
